defmodule Discussapp.Repo.Migrations.AddTopics do
  use Ecto.Migration
  @moduledoc """
  This file was generated by next command:
      iex> mix ecto.gen.migration add_topics
      To be able to migrate this, execute next command:
      iex> mix ecto.migrate
  """

  def change do
    # new table named 'topics', it will have a title and a string column
    create table(:topics) do
      add :title, :string
    end
  end
end
